### ISSUE TITLE
Cannot Build Plugin

### ISSUE THREAD

**Issue by dirkh71** [jenkinsci/ivy-plugin#41]
Hi,
i get this error while building the pluginin

> Task :compileJava
Caching disabled for task ':compileJava' because:
  Build cache is disabled
Task ':compileJava' is not up-to-date because:
  Task has failed previously.
The input changes require a full rebuild for incremental task ':compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with JDK Java compiler API.
Note: hudson.ivy.builder.AntIvyBuilderType.DescriptorImpl indexed under hudson.Extension
Note: hudson.ivy.builder.NAntIvyBuilderType.DescriptorImpl indexed under hudson.Extension
Note: hudson.ivy.IvyBuildTrigger.IvyConfiguration.DescriptorImpl indexed under hudson.Extension
Note: hudson.ivy.IvyBuildTrigger.DESCRIPTOR indexed under hudson.Extension
Note: hudson.ivy.IvyConfig.provider indexed under hudson.Extension
Note: hudson.ivy.IvyModuleSet.DESCRIPTOR indexed under hudson.Extension
error: java.nio.file.NoSuchFileException: C:\ivy-plugin-master\build\classes\java\main\META-INF\annotations\hudson.Extension
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

> Task :compileJava FAILED
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 12.476 secs.

Would be nice if someone can help me.

I like to change the class ModuleDependency. Because i don't want to build all dependencies.
So i like to change the following line like this
        this.revision = (revision == null || revision.startsWith("latest.integration") || revision.startsWith("working@") || revision.contains("${")) ? UNKNOWN : revision;

**Comment by arothian** [comment]
Hi @dirkh71 , I'm able to build from master successfully. Do you have local changes? It looks like you have a syntax error around `:`.

Since this does not appear to be an outstanding bug, I'm closing this.

**Comment by dirkh71** [comment]
Now i can build too, but i have to use Java8 , with java9 and above it is not possible
